baseURL = "https://qaz5823091.github.io/"
title = "羲加加的部落格"
paginate = 5
theme = "GithubPageThemes"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "羲加加的部落格"
description = "Record my coding life !"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "CPP"
# images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
disableSpecial1stPost = false
disableScrollToTop = false
showtoc = true

  # [params.assets]
  # favicon = "<link / abs url>"
  # favicon16x16 = "<link / abs url>"
  # favicon32x32 = "<link / abs url>"
  # apple_touch_icon = "<link / abs url>"
  # safari_pinned_tab = "<link / abs url>"

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "有問題歡迎聯繫我！"
  Content = "Contact me !"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/qaz5823091"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/steven.yeh.543"


  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/1010.0110.0110"


[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  # [params.editPost]
  # URL = "https://github.com/qaz5823091/content"
  # Text = "Suggest Changes"
  # appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
name = "Archives"
url = "/archives/"
weight = 10

[[menu.main]]
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "Tags"
name = "Tags"
url = "/tags/"
weight = 20
